version: '3.8'
services:
  mongo: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: pokeadmin
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local