version: '4.3'
services:
  monguito: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: pokeadmin
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - 5000:5000
    depends_on:
      - monguito
    volumes:
      - ./:/app

volumes:
  mongodata: