name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
    - shell: cmd
      env:
        SUPER_SECRET: ${{ secrets.SECRET_KEY }}
      run: |
        example-command "%SECRET_KEY%"
